export const API_URL = 'https://api.unsplash.com';
export const API_URL_PHOTOS = `${API_URL}/photos`;
export const API_URL_TOKEN = 'https://unsplash.com/oauth/token';
export const API_URL_AUTH = 'https://unsplash.com/oauth/authorize';
export const ACCESS_KEY = 'xtzygi-DEW2bCmVbJONvbymgTkKwoI-rVZZSL2-X9SI';
export const REDIRECT_URI = 'http://127.0.0.1:5500/PetProjects/17_js_photogallery/';
export const RESPONSE_TYPE = 'code';
export const SCOPE = 'public read_user read_photos write_likes';
export const SECRET_KEY = 'fHuP8AlNTxTmSJY5OlMVnIIN3SGqBwiTMX6-6FUiSJI';